#include "characters.h"

// TODO: rework this file with better data structures
const int CHAR_NAMES_COUNT = 41; // charNames.size();

const std::vector<std::string> charNames
{
	"Ragna",	// 0,
	"Jin",		// 1,
	"Noel",		// 2,
	"Rachel",	// 3,
	"Tager",	// 4,
	"Hakumen",	// 5,
	"Nu",		// 6,
	"Hazama",	// 7,
	"Makoto",	// 8,
	"Platinum", // 9,
	"Izayoi",	// 10,
	"Azrael",	// 11,
	"Nine",		// 12,
	"Es",		// 13,
	"Mai",		// 14,
	"Jubei",	// 15,
	"Yu",		// 16,
	"Yosuke",	// 17,
	"Chie",		// 18,
	"Yukiko",	// 19,
	"Kanji",	// 20,
	"Naoto",	// 21,
	"Mitsuru",	// 22,
	"Akihiko",	// 23,
	"Aegis",	// 24,
	"Labrys",	// 25,
	"Hyde",		// 26,
	"Linne",	// 27,
	"Waldstein",// 28,
	"Carmine",	// 29,
	"Orie",		// 30,
	"Gordeau",	// 31,
	"Merkava",	// 32,
	"Vatista",	// 33,
	"Yuzuriha",	// 34,
	"Mika",		// 35,
	"Ruby",		// 36,
	"Weiss",	// 37,
	"Blake",	// 38,
	"Yang",		// 39,
	"Boss",		// 40
};

const std::vector<std::wstring> wCharNames
{
	L"Ragna",	// 0,
	L"Jin",		// 1,
	L"Noel",	// 2,
	L"Rachel",	// 3,
	L"Tager",	// 4,
	L"Hakumen",	// 5,
	L"Nu",		// 6,
	L"Hazama",	// 7,
	L"Makoto",	// 8,
	L"Platinum", // 9,
	L"Izayoi",	// 10,
	L"Azrael",	// 11,
	L"Nine",	// 12,
	L"Es",		// 13,
	L"Mai",		// 14,
	L"Jubei",	// 15,
	L"Yu",		// 16,
	L"Yosuke",	// 17,
	L"Chie",	// 18,
	L"Yukiko",	// 19,
	L"Kanji",	// 20,
	L"Naoto",	// 21,
	L"Mitsuru",	// 22,
	L"Akihiko",	// 23,
	L"Aegis",	// 24,
	L"Labrys",	// 25,
	L"Hyde",	// 26,
	L"Linne",	// 27,
	L"Waldstein",// 28,
	L"Carmine",	// 29,
	L"Orie",	// 30,
	L"Gordeau",	// 31,
	L"Merkava",	// 32,
	L"Vatista",	// 33,
	L"Yuzuriha",// 34,
	L"Mika",	// 35,
	L"Ruby",	// 36,
	L"Weiss",	// 37,
	L"Blake",	// 38,
	L"Yang",	// 39,
	L"Boss",	// 40
};
